package com.zjgt.p2p.report.dao;

import com.zjgt.p2p.report.model.PaymentPlatForm;
import com.zjgt.p2p.report.model.PaymentPlatFormExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface PaymentPlatFormMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentplatform
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentplatform
     *
     * @mbggenerated
     */
    int insert(PaymentPlatForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentplatform
     *
     * @mbggenerated
     */
    int insertSelective(PaymentPlatForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentplatform
     *
     * @mbggenerated
     */
    List<PaymentPlatForm> selectByExample(PaymentPlatFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentplatform
     *
     * @mbggenerated
     */
    PaymentPlatForm selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentplatform
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PaymentPlatForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentplatform
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PaymentPlatForm record);
    
  //============自定义===========
    List<PaymentPlatForm> queryAll(@Param("pt")PaymentPlatForm pt);
}