package com.zjgt.p2p.report.dao;

import com.zjgt.p2p.report.model.PaymentPlatForm;
import com.zjgt.p2p.report.model.PlatFormType;
import com.zjgt.p2p.report.model.PlatFormTypeExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface PlatFormTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platformtype
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platformtype
     *
     * @mbggenerated
     */
    int insert(PlatFormType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platformtype
     *
     * @mbggenerated
     */
    int insertSelective(PlatFormType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platformtype
     *
     * @mbggenerated
     */
    List<PlatFormType> selectByExample(PlatFormTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platformtype
     *
     * @mbggenerated
     */
    PlatFormType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platformtype
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PlatFormType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platformtype
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PlatFormType record);
    
    
  //============自定义===========
    List<PlatFormType> queryAll(@Param("ptp")PlatFormType ptp);
}