package com.zjgt.p2p.report.dao;

import com.alibaba.model.easyui.PageHelper;
import com.zjgt.p2p.report.model.Sms_templates;
import com.zjgt.p2p.report.model.Sms_templatesExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface Sms_templatesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_templates
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_templates
     *
     * @mbggenerated
     */
    int insert(Sms_templates record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_templates
     *
     * @mbggenerated
     */
    int insertSelective(Sms_templates record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_templates
     *
     * @mbggenerated
     */
    List<Sms_templates> selectByExampleWithBLOBs(Sms_templatesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_templates
     *
     * @mbggenerated
     */
    List<Sms_templates> selectByExample(Sms_templatesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_templates
     *
     * @mbggenerated
     */
    Sms_templates selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_templates
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Sms_templates record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_templates
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Sms_templates record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_templates
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Sms_templates record);
    
    Long gettemplatesTotal(@Param("sc")Sms_templates sc);

	List<Sms_templates> gettemplatesData(@Param("page")PageHelper page,@Param("sc")Sms_templates sc);
	
	Sms_templates getSyncMoban(@Param("sgin")String sgin);

	long selectinsertData(@Param("sc") Sms_templates sc);
	
}