package com.zjgt.p2p.report.dao;

import com.zjgt.p2p.report.model.Sms_supplier;
import com.zjgt.p2p.report.model.Sms_supplierExample;
import java.util.List;

public interface Sms_supplierMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_supplier
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_supplier
     *
     * @mbggenerated
     */
    int insert(Sms_supplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_supplier
     *
     * @mbggenerated
     */
    int insertSelective(Sms_supplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_supplier
     *
     * @mbggenerated
     */
    List<Sms_supplier> selectByExample(Sms_supplierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_supplier
     *
     * @mbggenerated
     */
    Sms_supplier selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_supplier
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Sms_supplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_supplier
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Sms_supplier record);
}