package com.zjgt.p2p.report.dao;

import com.zjgt.p2p.report.model.OptranslogTemp;
import com.zjgt.p2p.report.model.Translog;
import com.zjgt.p2p.report.model.TranslogTemp;
import com.zjgt.p2p.report.model.TranslogTempExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface TranslogTempMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table translogtemp
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table translogtemp
     *
     * @mbggenerated
     */
    int insert(TranslogTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table translogtemp
     *
     * @mbggenerated
     */
    int insertSelective(TranslogTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table translogtemp
     *
     * @mbggenerated
     */
    List<TranslogTemp> selectByExample(TranslogTempExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table translogtemp
     *
     * @mbggenerated
     */
    TranslogTemp selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table translogtemp
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TranslogTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table translogtemp
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TranslogTemp record);
    
    /**
     * 分组统计平台金额
     * translog
     */
     void insertTsTempByGroup(@Param("tsTemp")TranslogTemp tsTemp);
     
     void delAll(TranslogTemp tsTemp);
     
     List<TranslogTemp> checkByGroup(TranslogTemp tsTemp);
}