package com.zjgt.p2p.report.model;

import java.util.Date;

public class Carddata {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carddata.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carddata.department
     *
     * @mbggenerated
     */
    private String department;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carddata.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carddata.carddate
     *
     * @mbggenerated
     */
    private Date carddate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carddata.id
     *
     * @return the value of carddata.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carddata.id
     *
     * @param id the value for carddata.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carddata.department
     *
     * @return the value of carddata.department
     *
     * @mbggenerated
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carddata.department
     *
     * @param department the value for carddata.department
     *
     * @mbggenerated
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carddata.username
     *
     * @return the value of carddata.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carddata.username
     *
     * @param username the value for carddata.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carddata.carddate
     *
     * @return the value of carddata.carddate
     *
     * @mbggenerated
     */
    public Date getCarddate() {
        return carddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carddata.carddate
     *
     * @param carddate the value for carddata.carddate
     *
     * @mbggenerated
     */
    public void setCarddate(Date carddate) {
        this.carddate = carddate;
    }
    
    private String starttime;
    
    public String getstarttime() {
  		return starttime;
  	}

  	public void setstarttime(String starttime) {
  		this.starttime = starttime;
  	}
  	
  private String endtime;
    
    public String getendtime() {
  		return endtime;
  	}

  	public void setendtime(String endtime) {
  		this.endtime = endtime;
  	}
  	
  private String mindate;
    
    public String getmindate() {
  		return mindate;
  	}

  	public void setmindate(String mindate) {
  		this.mindate = mindate;
  	}
  	
  private String maxdate;
    
    public String getmaxdate() {
  		return maxdate;
  	}

  	public void setmaxdate(String maxdate) {
  		this.maxdate = maxdate;
  	}
  	
  	
  	
    
}