package com.zjgt.p2p.report.model;

import java.util.Date;

public class MobileGuiShu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobileguishu.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobileguishu.mobile
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobileguishu.province
     *
     * @mbggenerated
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobileguishu.city
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobileguishu.areacode
     *
     * @mbggenerated
     */
    private String areacode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobileguishu.zip
     *
     * @mbggenerated
     */
    private String zip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobileguishu.company
     *
     * @mbggenerated
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobileguishu.card
     *
     * @mbggenerated
     */
    private String card;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobileguishu.errorcode
     *
     * @mbggenerated
     */
    private Integer errorcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobileguishu.reason
     *
     * @mbggenerated
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobileguishu.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobileguishu.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobileguishu.updtetime
     *
     * @mbggenerated
     */
    private Date updtetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobileguishu.temp1
     *
     * @mbggenerated
     */
    private String temp1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobileguishu.temp2
     *
     * @mbggenerated
     */
    private String temp2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobileguishu.temp3
     *
     * @mbggenerated
     */
    private String temp3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobileguishu.temp4
     *
     * @mbggenerated
     */
    private String temp4;
    
    private String beginTime;
    private String endTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobileguishu.id
     *
     * @return the value of mobileguishu.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobileguishu.id
     *
     * @param id the value for mobileguishu.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobileguishu.mobile
     *
     * @return the value of mobileguishu.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobileguishu.mobile
     *
     * @param mobile the value for mobileguishu.mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobileguishu.province
     *
     * @return the value of mobileguishu.province
     *
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobileguishu.province
     *
     * @param province the value for mobileguishu.province
     *
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobileguishu.city
     *
     * @return the value of mobileguishu.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobileguishu.city
     *
     * @param city the value for mobileguishu.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobileguishu.areacode
     *
     * @return the value of mobileguishu.areacode
     *
     * @mbggenerated
     */
    public String getAreacode() {
        return areacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobileguishu.areacode
     *
     * @param areacode the value for mobileguishu.areacode
     *
     * @mbggenerated
     */
    public void setAreacode(String areacode) {
        this.areacode = areacode == null ? null : areacode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobileguishu.zip
     *
     * @return the value of mobileguishu.zip
     *
     * @mbggenerated
     */
    public String getZip() {
        return zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobileguishu.zip
     *
     * @param zip the value for mobileguishu.zip
     *
     * @mbggenerated
     */
    public void setZip(String zip) {
        this.zip = zip == null ? null : zip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobileguishu.company
     *
     * @return the value of mobileguishu.company
     *
     * @mbggenerated
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobileguishu.company
     *
     * @param company the value for mobileguishu.company
     *
     * @mbggenerated
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobileguishu.card
     *
     * @return the value of mobileguishu.card
     *
     * @mbggenerated
     */
    public String getCard() {
        return card;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobileguishu.card
     *
     * @param card the value for mobileguishu.card
     *
     * @mbggenerated
     */
    public void setCard(String card) {
        this.card = card == null ? null : card.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobileguishu.errorcode
     *
     * @return the value of mobileguishu.errorcode
     *
     * @mbggenerated
     */
    public Integer getErrorcode() {
        return errorcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobileguishu.errorcode
     *
     * @param errorcode the value for mobileguishu.errorcode
     *
     * @mbggenerated
     */
    public void setErrorcode(Integer errorcode) {
        this.errorcode = errorcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobileguishu.reason
     *
     * @return the value of mobileguishu.reason
     *
     * @mbggenerated
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobileguishu.reason
     *
     * @param reason the value for mobileguishu.reason
     *
     * @mbggenerated
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobileguishu.username
     *
     * @return the value of mobileguishu.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobileguishu.username
     *
     * @param username the value for mobileguishu.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobileguishu.createtime
     *
     * @return the value of mobileguishu.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobileguishu.createtime
     *
     * @param createtime the value for mobileguishu.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobileguishu.updtetime
     *
     * @return the value of mobileguishu.updtetime
     *
     * @mbggenerated
     */
    public Date getUpdtetime() {
        return updtetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobileguishu.updtetime
     *
     * @param updtetime the value for mobileguishu.updtetime
     *
     * @mbggenerated
     */
    public void setUpdtetime(Date updtetime) {
        this.updtetime = updtetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobileguishu.temp1
     *
     * @return the value of mobileguishu.temp1
     *
     * @mbggenerated
     */
    public String getTemp1() {
        return temp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobileguishu.temp1
     *
     * @param temp1 the value for mobileguishu.temp1
     *
     * @mbggenerated
     */
    public void setTemp1(String temp1) {
        this.temp1 = temp1 == null ? null : temp1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobileguishu.temp2
     *
     * @return the value of mobileguishu.temp2
     *
     * @mbggenerated
     */
    public String getTemp2() {
        return temp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobileguishu.temp2
     *
     * @param temp2 the value for mobileguishu.temp2
     *
     * @mbggenerated
     */
    public void setTemp2(String temp2) {
        this.temp2 = temp2 == null ? null : temp2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobileguishu.temp3
     *
     * @return the value of mobileguishu.temp3
     *
     * @mbggenerated
     */
    public String getTemp3() {
        return temp3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobileguishu.temp3
     *
     * @param temp3 the value for mobileguishu.temp3
     *
     * @mbggenerated
     */
    public void setTemp3(String temp3) {
        this.temp3 = temp3 == null ? null : temp3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobileguishu.temp4
     *
     * @return the value of mobileguishu.temp4
     *
     * @mbggenerated
     */
    public String getTemp4() {
        return temp4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobileguishu.temp4
     *
     * @param temp4 the value for mobileguishu.temp4
     *
     * @mbggenerated
     */
    public void setTemp4(String temp4) {
        this.temp4 = temp4 == null ? null : temp4.trim();
    }

	public String getBeginTime()
	{
		return beginTime;
	}

	public void setBeginTime(String beginTime)
	{
		this.beginTime = beginTime;
	}

	public String getEndTime()
	{
		return endTime;
	}

	public void setEndTime(String endTime)
	{
		this.endTime = endTime;
	}
}