package com.zjgt.p2p.report.model;

import java.math.BigDecimal;

public class PaymentPlatForm {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paymentplatform.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paymentplatform.platForm
     *
     * @mbggenerated
     */
    private String platform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paymentplatform.interestType
     *
     * @mbggenerated
     */
    private String interesttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paymentplatform.computingMethod
     *
     * @mbggenerated
     */
    private String computingmethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paymentplatform.payMentInterest
     *
     * @mbggenerated
     */
    private BigDecimal paymentinterest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paymentplatform.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paymentplatform.temp1
     *
     * @mbggenerated
     */
    private String temp1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paymentplatform.temp2
     *
     * @mbggenerated
     */
    private String temp2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paymentplatform.temp3
     *
     * @mbggenerated
     */
    private String temp3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paymentplatform.temp4
     *
     * @mbggenerated
     */
    private String temp4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paymentplatform.temp5
     *
     * @mbggenerated
     */
    private String temp5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paymentplatform.id
     *
     * @return the value of paymentplatform.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paymentplatform.id
     *
     * @param id the value for paymentplatform.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paymentplatform.platForm
     *
     * @return the value of paymentplatform.platForm
     *
     * @mbggenerated
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paymentplatform.platForm
     *
     * @param platform the value for paymentplatform.platForm
     *
     * @mbggenerated
     */
    public void setPlatform(String platform) {
        this.platform = platform == null ? null : platform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paymentplatform.interestType
     *
     * @return the value of paymentplatform.interestType
     *
     * @mbggenerated
     */
    public String getInteresttype() {
        return interesttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paymentplatform.interestType
     *
     * @param interesttype the value for paymentplatform.interestType
     *
     * @mbggenerated
     */
    public void setInteresttype(String interesttype) {
        this.interesttype = interesttype == null ? null : interesttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paymentplatform.computingMethod
     *
     * @return the value of paymentplatform.computingMethod
     *
     * @mbggenerated
     */
    public String getComputingmethod() {
        return computingmethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paymentplatform.computingMethod
     *
     * @param computingmethod the value for paymentplatform.computingMethod
     *
     * @mbggenerated
     */
    public void setComputingmethod(String computingmethod) {
        this.computingmethod = computingmethod == null ? null : computingmethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paymentplatform.payMentInterest
     *
     * @return the value of paymentplatform.payMentInterest
     *
     * @mbggenerated
     */
    public BigDecimal getPaymentinterest() {
        return paymentinterest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paymentplatform.payMentInterest
     *
     * @param paymentinterest the value for paymentplatform.payMentInterest
     *
     * @mbggenerated
     */
    public void setPaymentinterest(BigDecimal paymentinterest) {
        this.paymentinterest = paymentinterest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paymentplatform.remark
     *
     * @return the value of paymentplatform.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paymentplatform.remark
     *
     * @param remark the value for paymentplatform.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paymentplatform.temp1
     *
     * @return the value of paymentplatform.temp1
     *
     * @mbggenerated
     */
    public String getTemp1() {
        return temp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paymentplatform.temp1
     *
     * @param temp1 the value for paymentplatform.temp1
     *
     * @mbggenerated
     */
    public void setTemp1(String temp1) {
        this.temp1 = temp1 == null ? null : temp1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paymentplatform.temp2
     *
     * @return the value of paymentplatform.temp2
     *
     * @mbggenerated
     */
    public String getTemp2() {
        return temp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paymentplatform.temp2
     *
     * @param temp2 the value for paymentplatform.temp2
     *
     * @mbggenerated
     */
    public void setTemp2(String temp2) {
        this.temp2 = temp2 == null ? null : temp2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paymentplatform.temp3
     *
     * @return the value of paymentplatform.temp3
     *
     * @mbggenerated
     */
    public String getTemp3() {
        return temp3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paymentplatform.temp3
     *
     * @param temp3 the value for paymentplatform.temp3
     *
     * @mbggenerated
     */
    public void setTemp3(String temp3) {
        this.temp3 = temp3 == null ? null : temp3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paymentplatform.temp4
     *
     * @return the value of paymentplatform.temp4
     *
     * @mbggenerated
     */
    public String getTemp4() {
        return temp4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paymentplatform.temp4
     *
     * @param temp4 the value for paymentplatform.temp4
     *
     * @mbggenerated
     */
    public void setTemp4(String temp4) {
        this.temp4 = temp4 == null ? null : temp4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paymentplatform.temp5
     *
     * @return the value of paymentplatform.temp5
     *
     * @mbggenerated
     */
    public String getTemp5() {
        return temp5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paymentplatform.temp5
     *
     * @param temp5 the value for paymentplatform.temp5
     *
     * @mbggenerated
     */
    public void setTemp5(String temp5) {
        this.temp5 = temp5 == null ? null : temp5.trim();
    }
    
    
  //=============自定义===============
    private String isCheck;
    private String interesttypename;
    private String computingmethodname;
    private String platformname;
    
    public String getPlatformname() {
		return platformname;
	}

	public void setPlatformname(String platformname) {
		this.platformname = platformname;
	}

	public String getInteresttypename() {
		return interesttypename;
	}

	public void setInteresttypename(String interesttypename) {
		this.interesttypename = interesttypename;
	}

	public String getComputingmethodname() {
		return computingmethodname;
	}

	public void setComputingmethodname(String computingmethodname) {
		this.computingmethodname = computingmethodname;
	}

	public String getisCheck() {
  		return isCheck;
  	}

  	public void setisCheck(String isCheck) {
  		this.isCheck = isCheck;
  	}
}