package com.zjgt.p2p.report.model;

public class PlatFormType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platformtype.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platformtype.plateFormId
     *
     * @mbggenerated
     */
    private Integer plateformid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platformtype.checkIn
     *
     * @mbggenerated
     */
    private Integer checkin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platformtype.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platformtype.temp1
     *
     * @mbggenerated
     */
    private String temp1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platformtype.temp2
     *
     * @mbggenerated
     */
    private String temp2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platformtype.temp3
     *
     * @mbggenerated
     */
    private String temp3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platformtype.temp4
     *
     * @mbggenerated
     */
    private String temp4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platformtype.temp5
     *
     * @mbggenerated
     */
    private String temp5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platformtype.id
     *
     * @return the value of platformtype.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platformtype.id
     *
     * @param id the value for platformtype.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platformtype.plateFormId
     *
     * @return the value of platformtype.plateFormId
     *
     * @mbggenerated
     */
    public Integer getPlateformid() {
        return plateformid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platformtype.plateFormId
     *
     * @param plateformid the value for platformtype.plateFormId
     *
     * @mbggenerated
     */
    public void setPlateformid(Integer plateformid) {
        this.plateformid = plateformid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platformtype.checkIn
     *
     * @return the value of platformtype.checkIn
     *
     * @mbggenerated
     */
    public Integer getCheckin() {
        return checkin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platformtype.checkIn
     *
     * @param checkin the value for platformtype.checkIn
     *
     * @mbggenerated
     */
    public void setCheckin(Integer checkin) {
        this.checkin = checkin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platformtype.remark
     *
     * @return the value of platformtype.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platformtype.remark
     *
     * @param remark the value for platformtype.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platformtype.temp1
     *
     * @return the value of platformtype.temp1
     *
     * @mbggenerated
     */
    public String getTemp1() {
        return temp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platformtype.temp1
     *
     * @param temp1 the value for platformtype.temp1
     *
     * @mbggenerated
     */
    public void setTemp1(String temp1) {
        this.temp1 = temp1 == null ? null : temp1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platformtype.temp2
     *
     * @return the value of platformtype.temp2
     *
     * @mbggenerated
     */
    public String getTemp2() {
        return temp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platformtype.temp2
     *
     * @param temp2 the value for platformtype.temp2
     *
     * @mbggenerated
     */
    public void setTemp2(String temp2) {
        this.temp2 = temp2 == null ? null : temp2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platformtype.temp3
     *
     * @return the value of platformtype.temp3
     *
     * @mbggenerated
     */
    public String getTemp3() {
        return temp3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platformtype.temp3
     *
     * @param temp3 the value for platformtype.temp3
     *
     * @mbggenerated
     */
    public void setTemp3(String temp3) {
        this.temp3 = temp3 == null ? null : temp3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platformtype.temp4
     *
     * @return the value of platformtype.temp4
     *
     * @mbggenerated
     */
    public String getTemp4() {
        return temp4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platformtype.temp4
     *
     * @param temp4 the value for platformtype.temp4
     *
     * @mbggenerated
     */
    public void setTemp4(String temp4) {
        this.temp4 = temp4 == null ? null : temp4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platformtype.temp5
     *
     * @return the value of platformtype.temp5
     *
     * @mbggenerated
     */
    public String getTemp5() {
        return temp5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platformtype.temp5
     *
     * @param temp5 the value for platformtype.temp5
     *
     * @mbggenerated
     */
    public void setTemp5(String temp5) {
        this.temp5 = temp5 == null ? null : temp5.trim();
    }
    
    private String isCheck;
    private String plateformname;
    private String checkinname;
    
    
    public String getPlateformname() {
		return plateformname;
	}

	public void setPlateformname(String plateformname) {
		this.plateformname = plateformname;
	}

	public String getCheckinname() {
		return checkinname;
	}

	public void setCheckinname(String checkinname) {
		this.checkinname = checkinname;
	}

	public String getisCheck() {
  		return isCheck;
  	}

  	public void setisCheck(String isCheck) {
  		this.isCheck = isCheck;
  	}
  	
}