package com.zjgt.p2p.report.model;

import java.util.Date;

public class rbPayment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rb_payment.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rb_payment.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rb_payment.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rb_payment.returnvalue
     *
     * @mbggenerated
     */
    private String returnvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rb_payment.cardtype
     *
     * @mbggenerated
     */
    private Integer cardtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rb_payment.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rb_payment.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rb_payment.temp1
     *
     * @mbggenerated
     */
    private String temp1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rb_payment.temp2
     *
     * @mbggenerated
     */
    private String temp2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rb_payment.temp3
     *
     * @mbggenerated
     */
    private String temp3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rb_payment.temp4
     *
     * @mbggenerated
     */
    private String temp4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rb_payment.temp5
     *
     * @mbggenerated
     */
    private String temp5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rb_payment.receivevalue
     *
     * @mbggenerated
     */
    private String receivevalue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rb_payment.id
     *
     * @return the value of rb_payment.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rb_payment.id
     *
     * @param id the value for rb_payment.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rb_payment.status
     *
     * @return the value of rb_payment.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rb_payment.status
     *
     * @param status the value for rb_payment.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rb_payment.username
     *
     * @return the value of rb_payment.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rb_payment.username
     *
     * @param username the value for rb_payment.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rb_payment.returnvalue
     *
     * @return the value of rb_payment.returnvalue
     *
     * @mbggenerated
     */
    public String getReturnvalue() {
        return returnvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rb_payment.returnvalue
     *
     * @param returnvalue the value for rb_payment.returnvalue
     *
     * @mbggenerated
     */
    public void setReturnvalue(String returnvalue) {
        this.returnvalue = returnvalue == null ? null : returnvalue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rb_payment.cardtype
     *
     * @return the value of rb_payment.cardtype
     *
     * @mbggenerated
     */
    public Integer getCardtype() {
        return cardtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rb_payment.cardtype
     *
     * @param cardtype the value for rb_payment.cardtype
     *
     * @mbggenerated
     */
    public void setCardtype(Integer cardtype) {
        this.cardtype = cardtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rb_payment.createtime
     *
     * @return the value of rb_payment.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rb_payment.createtime
     *
     * @param createtime the value for rb_payment.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rb_payment.remark
     *
     * @return the value of rb_payment.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rb_payment.remark
     *
     * @param remark the value for rb_payment.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rb_payment.temp1
     *
     * @return the value of rb_payment.temp1
     *
     * @mbggenerated
     */
    public String getTemp1() {
        return temp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rb_payment.temp1
     *
     * @param temp1 the value for rb_payment.temp1
     *
     * @mbggenerated
     */
    public void setTemp1(String temp1) {
        this.temp1 = temp1 == null ? null : temp1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rb_payment.temp2
     *
     * @return the value of rb_payment.temp2
     *
     * @mbggenerated
     */
    public String getTemp2() {
        return temp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rb_payment.temp2
     *
     * @param temp2 the value for rb_payment.temp2
     *
     * @mbggenerated
     */
    public void setTemp2(String temp2) {
        this.temp2 = temp2 == null ? null : temp2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rb_payment.temp3
     *
     * @return the value of rb_payment.temp3
     *
     * @mbggenerated
     */
    public String getTemp3() {
        return temp3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rb_payment.temp3
     *
     * @param temp3 the value for rb_payment.temp3
     *
     * @mbggenerated
     */
    public void setTemp3(String temp3) {
        this.temp3 = temp3 == null ? null : temp3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rb_payment.temp4
     *
     * @return the value of rb_payment.temp4
     *
     * @mbggenerated
     */
    public String getTemp4() {
        return temp4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rb_payment.temp4
     *
     * @param temp4 the value for rb_payment.temp4
     *
     * @mbggenerated
     */
    public void setTemp4(String temp4) {
        this.temp4 = temp4 == null ? null : temp4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rb_payment.temp5
     *
     * @return the value of rb_payment.temp5
     *
     * @mbggenerated
     */
    public String getTemp5() {
        return temp5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rb_payment.temp5
     *
     * @param temp5 the value for rb_payment.temp5
     *
     * @mbggenerated
     */
    public void setTemp5(String temp5) {
        this.temp5 = temp5 == null ? null : temp5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rb_payment.receivevalue
     *
     * @return the value of rb_payment.receivevalue
     *
     * @mbggenerated
     */
    public String getReceivevalue() {
        return receivevalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rb_payment.receivevalue
     *
     * @param receivevalue the value for rb_payment.receivevalue
     *
     * @mbggenerated
     */
    public void setReceivevalue(String receivevalue) {
        this.receivevalue = receivevalue == null ? null : receivevalue.trim();
    }
    
    private String starttime;
    private String endtime;

	public String getStarttime() {
		return starttime;
	}

	public void setStarttime(String starttime) {
		this.starttime = starttime;
	}

	public String getEndtime() {
		return endtime;
	}

	public void setEndtime(String endtime) {
		this.endtime = endtime;
	}
    
	private String isCheck;

	public String getIsCheck() {
		return isCheck;
	}

	public void setIsCheck(String isCheck) {
		this.isCheck = isCheck;
	}
	
	private String statusname;

	public String getStatusname() {
		return statusname;
	}

	public void setStatusname(String statusname) {
		this.statusname = statusname;
	}
    
	private String cardstatus;

	public String getCardstatus() {
		return cardstatus;
	}

	public void setCardstatus(String cardstatus) {
		this.cardstatus = cardstatus;
	}
	
    
}