package com.zjgt.p2p.report.model;

import java.util.Date;

public class Sms_lcinfos {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_lcinfos.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_lcinfos.soure
     *
     * @mbggenerated
     */
    private Integer soure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_lcinfos.suppliername
     *
     * @mbggenerated
     */
    private String suppliername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_lcinfos.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_lcinfos.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_lcinfos.netguid
     *
     * @mbggenerated
     */
    private String netguid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_lcinfos.smsvalue
     *
     * @mbggenerated
     */
    private String smsvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_lcinfos.senddate
     *
     * @mbggenerated
     */
    private Date senddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_lcinfos.temp1
     *
     * @mbggenerated
     */
    private String temp1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_lcinfos.temp2
     *
     * @mbggenerated
     */
    private String temp2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_lcinfos.temp3
     *
     * @mbggenerated
     */
    private String temp3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_lcinfos.temp4
     *
     * @mbggenerated
     */
    private String temp4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_lcinfos.temp5
     *
     * @mbggenerated
     */
    private String temp5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_lcinfos.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_lcinfos.id
     *
     * @return the value of sms_lcinfos.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_lcinfos.id
     *
     * @param id the value for sms_lcinfos.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_lcinfos.soure
     *
     * @return the value of sms_lcinfos.soure
     *
     * @mbggenerated
     */
    public Integer getSoure() {
        return soure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_lcinfos.soure
     *
     * @param soure the value for sms_lcinfos.soure
     *
     * @mbggenerated
     */
    public void setSoure(Integer soure) {
        this.soure = soure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_lcinfos.suppliername
     *
     * @return the value of sms_lcinfos.suppliername
     *
     * @mbggenerated
     */
    public String getSuppliername() {
        return suppliername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_lcinfos.suppliername
     *
     * @param suppliername the value for sms_lcinfos.suppliername
     *
     * @mbggenerated
     */
    public void setSuppliername(String suppliername) {
        this.suppliername = suppliername == null ? null : suppliername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_lcinfos.username
     *
     * @return the value of sms_lcinfos.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_lcinfos.username
     *
     * @param username the value for sms_lcinfos.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_lcinfos.status
     *
     * @return the value of sms_lcinfos.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_lcinfos.status
     *
     * @param status the value for sms_lcinfos.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_lcinfos.netguid
     *
     * @return the value of sms_lcinfos.netguid
     *
     * @mbggenerated
     */
    public String getNetguid() {
        return netguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_lcinfos.netguid
     *
     * @param netguid the value for sms_lcinfos.netguid
     *
     * @mbggenerated
     */
    public void setNetguid(String netguid) {
        this.netguid = netguid == null ? null : netguid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_lcinfos.smsvalue
     *
     * @return the value of sms_lcinfos.smsvalue
     *
     * @mbggenerated
     */
    public String getSmsvalue() {
        return smsvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_lcinfos.smsvalue
     *
     * @param smsvalue the value for sms_lcinfos.smsvalue
     *
     * @mbggenerated
     */
    public void setSmsvalue(String smsvalue) {
        this.smsvalue = smsvalue == null ? null : smsvalue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_lcinfos.senddate
     *
     * @return the value of sms_lcinfos.senddate
     *
     * @mbggenerated
     */
    public Date getSenddate() {
        return senddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_lcinfos.senddate
     *
     * @param senddate the value for sms_lcinfos.senddate
     *
     * @mbggenerated
     */
    public void setSenddate(Date senddate) {
        this.senddate = senddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_lcinfos.temp1
     *
     * @return the value of sms_lcinfos.temp1
     *
     * @mbggenerated
     */
    public String getTemp1() {
        return temp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_lcinfos.temp1
     *
     * @param temp1 the value for sms_lcinfos.temp1
     *
     * @mbggenerated
     */
    public void setTemp1(String temp1) {
        this.temp1 = temp1 == null ? null : temp1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_lcinfos.temp2
     *
     * @return the value of sms_lcinfos.temp2
     *
     * @mbggenerated
     */
    public String getTemp2() {
        return temp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_lcinfos.temp2
     *
     * @param temp2 the value for sms_lcinfos.temp2
     *
     * @mbggenerated
     */
    public void setTemp2(String temp2) {
        this.temp2 = temp2 == null ? null : temp2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_lcinfos.temp3
     *
     * @return the value of sms_lcinfos.temp3
     *
     * @mbggenerated
     */
    public String getTemp3() {
        return temp3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_lcinfos.temp3
     *
     * @param temp3 the value for sms_lcinfos.temp3
     *
     * @mbggenerated
     */
    public void setTemp3(String temp3) {
        this.temp3 = temp3 == null ? null : temp3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_lcinfos.temp4
     *
     * @return the value of sms_lcinfos.temp4
     *
     * @mbggenerated
     */
    public String getTemp4() {
        return temp4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_lcinfos.temp4
     *
     * @param temp4 the value for sms_lcinfos.temp4
     *
     * @mbggenerated
     */
    public void setTemp4(String temp4) {
        this.temp4 = temp4 == null ? null : temp4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_lcinfos.temp5
     *
     * @return the value of sms_lcinfos.temp5
     *
     * @mbggenerated
     */
    public String getTemp5() {
        return temp5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_lcinfos.temp5
     *
     * @param temp5 the value for sms_lcinfos.temp5
     *
     * @mbggenerated
     */
    public void setTemp5(String temp5) {
        this.temp5 = temp5 == null ? null : temp5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_lcinfos.content
     *
     * @return the value of sms_lcinfos.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_lcinfos.content
     *
     * @param content the value for sms_lcinfos.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
    
private String starttime;
    
    
   	public String getstarttime() {
   		return starttime;
   	}

   	public void setstarttime(String starttime) {
   		this.starttime = starttime;
   	}

   	private String endtime;
    
    
   	public String getendtime() {
   		return endtime;
   	}

   	public void setendtime(String endtime) {
   		this.endtime = endtime;
   	}
    
	private String isCheck;
	
    public String getisCheck() {
  		return isCheck;
  	}

  	public void setisCheck(String isCheck) {
  		this.isCheck = isCheck;
  	}
    
  	private String sendstatus;
	
    public String getsendstatus() {
  		return sendstatus;
  	}

  	public void setsendstatus(String sendstatus) {
  		this.sendstatus = sendstatus;
  	}
  	
	private String sourename;
	
    public String getsourename() {
  		return sourename;
  	}

  	public void setsourename(String sourename) {
  		this.sourename = sourename;
  	}
  	
  	
	private String projectType;
	
    public String getprojectType() {
  		return projectType;
  	}

  	public void setprojectType(String projectType) {
  		this.projectType = projectType;
  	}
  	
    
}