package com.zjgt.p2p.report.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class Sms_templatesExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sms_templates
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sms_templates
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sms_templates
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_templates
     *
     * @mbggenerated
     */
    public Sms_templatesExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_templates
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_templates
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_templates
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_templates
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_templates
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_templates
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_templates
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_templates
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_templates
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_templates
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sms_templates
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSignboardIsNull() {
            addCriterion("signboard is null");
            return (Criteria) this;
        }

        public Criteria andSignboardIsNotNull() {
            addCriterion("signboard is not null");
            return (Criteria) this;
        }

        public Criteria andSignboardEqualTo(String value) {
            addCriterion("signboard =", value, "signboard");
            return (Criteria) this;
        }

        public Criteria andSignboardNotEqualTo(String value) {
            addCriterion("signboard <>", value, "signboard");
            return (Criteria) this;
        }

        public Criteria andSignboardGreaterThan(String value) {
            addCriterion("signboard >", value, "signboard");
            return (Criteria) this;
        }

        public Criteria andSignboardGreaterThanOrEqualTo(String value) {
            addCriterion("signboard >=", value, "signboard");
            return (Criteria) this;
        }

        public Criteria andSignboardLessThan(String value) {
            addCriterion("signboard <", value, "signboard");
            return (Criteria) this;
        }

        public Criteria andSignboardLessThanOrEqualTo(String value) {
            addCriterion("signboard <=", value, "signboard");
            return (Criteria) this;
        }

        public Criteria andSignboardLike(String value) {
            addCriterion("signboard like", value, "signboard");
            return (Criteria) this;
        }

        public Criteria andSignboardNotLike(String value) {
            addCriterion("signboard not like", value, "signboard");
            return (Criteria) this;
        }

        public Criteria andSignboardIn(List<String> values) {
            addCriterion("signboard in", values, "signboard");
            return (Criteria) this;
        }

        public Criteria andSignboardNotIn(List<String> values) {
            addCriterion("signboard not in", values, "signboard");
            return (Criteria) this;
        }

        public Criteria andSignboardBetween(String value1, String value2) {
            addCriterion("signboard between", value1, value2, "signboard");
            return (Criteria) this;
        }

        public Criteria andSignboardNotBetween(String value1, String value2) {
            addCriterion("signboard not between", value1, value2, "signboard");
            return (Criteria) this;
        }

        public Criteria andIscheckIsNull() {
            addCriterion("ischeck is null");
            return (Criteria) this;
        }

        public Criteria andIscheckIsNotNull() {
            addCriterion("ischeck is not null");
            return (Criteria) this;
        }

        public Criteria andIscheckEqualTo(Integer value) {
            addCriterion("ischeck =", value, "ischeck");
            return (Criteria) this;
        }

        public Criteria andIscheckNotEqualTo(Integer value) {
            addCriterion("ischeck <>", value, "ischeck");
            return (Criteria) this;
        }

        public Criteria andIscheckGreaterThan(Integer value) {
            addCriterion("ischeck >", value, "ischeck");
            return (Criteria) this;
        }

        public Criteria andIscheckGreaterThanOrEqualTo(Integer value) {
            addCriterion("ischeck >=", value, "ischeck");
            return (Criteria) this;
        }

        public Criteria andIscheckLessThan(Integer value) {
            addCriterion("ischeck <", value, "ischeck");
            return (Criteria) this;
        }

        public Criteria andIscheckLessThanOrEqualTo(Integer value) {
            addCriterion("ischeck <=", value, "ischeck");
            return (Criteria) this;
        }

        public Criteria andIscheckIn(List<Integer> values) {
            addCriterion("ischeck in", values, "ischeck");
            return (Criteria) this;
        }

        public Criteria andIscheckNotIn(List<Integer> values) {
            addCriterion("ischeck not in", values, "ischeck");
            return (Criteria) this;
        }

        public Criteria andIscheckBetween(Integer value1, Integer value2) {
            addCriterion("ischeck between", value1, value2, "ischeck");
            return (Criteria) this;
        }

        public Criteria andIscheckNotBetween(Integer value1, Integer value2) {
            addCriterion("ischeck not between", value1, value2, "ischeck");
            return (Criteria) this;
        }

        public Criteria andChecknameIsNull() {
            addCriterion("checkname is null");
            return (Criteria) this;
        }

        public Criteria andChecknameIsNotNull() {
            addCriterion("checkname is not null");
            return (Criteria) this;
        }

        public Criteria andChecknameEqualTo(String value) {
            addCriterion("checkname =", value, "checkname");
            return (Criteria) this;
        }

        public Criteria andChecknameNotEqualTo(String value) {
            addCriterion("checkname <>", value, "checkname");
            return (Criteria) this;
        }

        public Criteria andChecknameGreaterThan(String value) {
            addCriterion("checkname >", value, "checkname");
            return (Criteria) this;
        }

        public Criteria andChecknameGreaterThanOrEqualTo(String value) {
            addCriterion("checkname >=", value, "checkname");
            return (Criteria) this;
        }

        public Criteria andChecknameLessThan(String value) {
            addCriterion("checkname <", value, "checkname");
            return (Criteria) this;
        }

        public Criteria andChecknameLessThanOrEqualTo(String value) {
            addCriterion("checkname <=", value, "checkname");
            return (Criteria) this;
        }

        public Criteria andChecknameLike(String value) {
            addCriterion("checkname like", value, "checkname");
            return (Criteria) this;
        }

        public Criteria andChecknameNotLike(String value) {
            addCriterion("checkname not like", value, "checkname");
            return (Criteria) this;
        }

        public Criteria andChecknameIn(List<String> values) {
            addCriterion("checkname in", values, "checkname");
            return (Criteria) this;
        }

        public Criteria andChecknameNotIn(List<String> values) {
            addCriterion("checkname not in", values, "checkname");
            return (Criteria) this;
        }

        public Criteria andChecknameBetween(String value1, String value2) {
            addCriterion("checkname between", value1, value2, "checkname");
            return (Criteria) this;
        }

        public Criteria andChecknameNotBetween(String value1, String value2) {
            addCriterion("checkname not between", value1, value2, "checkname");
            return (Criteria) this;
        }

        public Criteria andChecktimeIsNull() {
            addCriterion("checktime is null");
            return (Criteria) this;
        }

        public Criteria andChecktimeIsNotNull() {
            addCriterion("checktime is not null");
            return (Criteria) this;
        }

        public Criteria andChecktimeEqualTo(Date value) {
            addCriterion("checktime =", value, "checktime");
            return (Criteria) this;
        }

        public Criteria andChecktimeNotEqualTo(Date value) {
            addCriterion("checktime <>", value, "checktime");
            return (Criteria) this;
        }

        public Criteria andChecktimeGreaterThan(Date value) {
            addCriterion("checktime >", value, "checktime");
            return (Criteria) this;
        }

        public Criteria andChecktimeGreaterThanOrEqualTo(Date value) {
            addCriterion("checktime >=", value, "checktime");
            return (Criteria) this;
        }

        public Criteria andChecktimeLessThan(Date value) {
            addCriterion("checktime <", value, "checktime");
            return (Criteria) this;
        }

        public Criteria andChecktimeLessThanOrEqualTo(Date value) {
            addCriterion("checktime <=", value, "checktime");
            return (Criteria) this;
        }

        public Criteria andChecktimeIn(List<Date> values) {
            addCriterion("checktime in", values, "checktime");
            return (Criteria) this;
        }

        public Criteria andChecktimeNotIn(List<Date> values) {
            addCriterion("checktime not in", values, "checktime");
            return (Criteria) this;
        }

        public Criteria andChecktimeBetween(Date value1, Date value2) {
            addCriterion("checktime between", value1, value2, "checktime");
            return (Criteria) this;
        }

        public Criteria andChecktimeNotBetween(Date value1, Date value2) {
            addCriterion("checktime not between", value1, value2, "checktime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createtime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createtime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("createtime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("createtime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("createtime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createtime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("createtime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("createtime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("createtime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("createtime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("createtime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("createtime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andProposernameIsNull() {
            addCriterion("proposername is null");
            return (Criteria) this;
        }

        public Criteria andProposernameIsNotNull() {
            addCriterion("proposername is not null");
            return (Criteria) this;
        }

        public Criteria andProposernameEqualTo(String value) {
            addCriterion("proposername =", value, "proposername");
            return (Criteria) this;
        }

        public Criteria andProposernameNotEqualTo(String value) {
            addCriterion("proposername <>", value, "proposername");
            return (Criteria) this;
        }

        public Criteria andProposernameGreaterThan(String value) {
            addCriterion("proposername >", value, "proposername");
            return (Criteria) this;
        }

        public Criteria andProposernameGreaterThanOrEqualTo(String value) {
            addCriterion("proposername >=", value, "proposername");
            return (Criteria) this;
        }

        public Criteria andProposernameLessThan(String value) {
            addCriterion("proposername <", value, "proposername");
            return (Criteria) this;
        }

        public Criteria andProposernameLessThanOrEqualTo(String value) {
            addCriterion("proposername <=", value, "proposername");
            return (Criteria) this;
        }

        public Criteria andProposernameLike(String value) {
            addCriterion("proposername like", value, "proposername");
            return (Criteria) this;
        }

        public Criteria andProposernameNotLike(String value) {
            addCriterion("proposername not like", value, "proposername");
            return (Criteria) this;
        }

        public Criteria andProposernameIn(List<String> values) {
            addCriterion("proposername in", values, "proposername");
            return (Criteria) this;
        }

        public Criteria andProposernameNotIn(List<String> values) {
            addCriterion("proposername not in", values, "proposername");
            return (Criteria) this;
        }

        public Criteria andProposernameBetween(String value1, String value2) {
            addCriterion("proposername between", value1, value2, "proposername");
            return (Criteria) this;
        }

        public Criteria andProposernameNotBetween(String value1, String value2) {
            addCriterion("proposername not between", value1, value2, "proposername");
            return (Criteria) this;
        }

        public Criteria andProposertimeIsNull() {
            addCriterion("proposertime is null");
            return (Criteria) this;
        }

        public Criteria andProposertimeIsNotNull() {
            addCriterion("proposertime is not null");
            return (Criteria) this;
        }

        public Criteria andProposertimeEqualTo(Date value) {
            addCriterion("proposertime =", value, "proposertime");
            return (Criteria) this;
        }

        public Criteria andProposertimeNotEqualTo(Date value) {
            addCriterion("proposertime <>", value, "proposertime");
            return (Criteria) this;
        }

        public Criteria andProposertimeGreaterThan(Date value) {
            addCriterion("proposertime >", value, "proposertime");
            return (Criteria) this;
        }

        public Criteria andProposertimeGreaterThanOrEqualTo(Date value) {
            addCriterion("proposertime >=", value, "proposertime");
            return (Criteria) this;
        }

        public Criteria andProposertimeLessThan(Date value) {
            addCriterion("proposertime <", value, "proposertime");
            return (Criteria) this;
        }

        public Criteria andProposertimeLessThanOrEqualTo(Date value) {
            addCriterion("proposertime <=", value, "proposertime");
            return (Criteria) this;
        }

        public Criteria andProposertimeIn(List<Date> values) {
            addCriterion("proposertime in", values, "proposertime");
            return (Criteria) this;
        }

        public Criteria andProposertimeNotIn(List<Date> values) {
            addCriterion("proposertime not in", values, "proposertime");
            return (Criteria) this;
        }

        public Criteria andProposertimeBetween(Date value1, Date value2) {
            addCriterion("proposertime between", value1, value2, "proposertime");
            return (Criteria) this;
        }

        public Criteria andProposertimeNotBetween(Date value1, Date value2) {
            addCriterion("proposertime not between", value1, value2, "proposertime");
            return (Criteria) this;
        }

        public Criteria andProposerremarkIsNull() {
            addCriterion("proposerremark is null");
            return (Criteria) this;
        }

        public Criteria andProposerremarkIsNotNull() {
            addCriterion("proposerremark is not null");
            return (Criteria) this;
        }

        public Criteria andProposerremarkEqualTo(String value) {
            addCriterion("proposerremark =", value, "proposerremark");
            return (Criteria) this;
        }

        public Criteria andProposerremarkNotEqualTo(String value) {
            addCriterion("proposerremark <>", value, "proposerremark");
            return (Criteria) this;
        }

        public Criteria andProposerremarkGreaterThan(String value) {
            addCriterion("proposerremark >", value, "proposerremark");
            return (Criteria) this;
        }

        public Criteria andProposerremarkGreaterThanOrEqualTo(String value) {
            addCriterion("proposerremark >=", value, "proposerremark");
            return (Criteria) this;
        }

        public Criteria andProposerremarkLessThan(String value) {
            addCriterion("proposerremark <", value, "proposerremark");
            return (Criteria) this;
        }

        public Criteria andProposerremarkLessThanOrEqualTo(String value) {
            addCriterion("proposerremark <=", value, "proposerremark");
            return (Criteria) this;
        }

        public Criteria andProposerremarkLike(String value) {
            addCriterion("proposerremark like", value, "proposerremark");
            return (Criteria) this;
        }

        public Criteria andProposerremarkNotLike(String value) {
            addCriterion("proposerremark not like", value, "proposerremark");
            return (Criteria) this;
        }

        public Criteria andProposerremarkIn(List<String> values) {
            addCriterion("proposerremark in", values, "proposerremark");
            return (Criteria) this;
        }

        public Criteria andProposerremarkNotIn(List<String> values) {
            addCriterion("proposerremark not in", values, "proposerremark");
            return (Criteria) this;
        }

        public Criteria andProposerremarkBetween(String value1, String value2) {
            addCriterion("proposerremark between", value1, value2, "proposerremark");
            return (Criteria) this;
        }

        public Criteria andProposerremarkNotBetween(String value1, String value2) {
            addCriterion("proposerremark not between", value1, value2, "proposerremark");
            return (Criteria) this;
        }

        public Criteria andTemp1IsNull() {
            addCriterion("temp1 is null");
            return (Criteria) this;
        }

        public Criteria andTemp1IsNotNull() {
            addCriterion("temp1 is not null");
            return (Criteria) this;
        }

        public Criteria andTemp1EqualTo(String value) {
            addCriterion("temp1 =", value, "temp1");
            return (Criteria) this;
        }

        public Criteria andTemp1NotEqualTo(String value) {
            addCriterion("temp1 <>", value, "temp1");
            return (Criteria) this;
        }

        public Criteria andTemp1GreaterThan(String value) {
            addCriterion("temp1 >", value, "temp1");
            return (Criteria) this;
        }

        public Criteria andTemp1GreaterThanOrEqualTo(String value) {
            addCriterion("temp1 >=", value, "temp1");
            return (Criteria) this;
        }

        public Criteria andTemp1LessThan(String value) {
            addCriterion("temp1 <", value, "temp1");
            return (Criteria) this;
        }

        public Criteria andTemp1LessThanOrEqualTo(String value) {
            addCriterion("temp1 <=", value, "temp1");
            return (Criteria) this;
        }

        public Criteria andTemp1Like(String value) {
            addCriterion("temp1 like", value, "temp1");
            return (Criteria) this;
        }

        public Criteria andTemp1NotLike(String value) {
            addCriterion("temp1 not like", value, "temp1");
            return (Criteria) this;
        }

        public Criteria andTemp1In(List<String> values) {
            addCriterion("temp1 in", values, "temp1");
            return (Criteria) this;
        }

        public Criteria andTemp1NotIn(List<String> values) {
            addCriterion("temp1 not in", values, "temp1");
            return (Criteria) this;
        }

        public Criteria andTemp1Between(String value1, String value2) {
            addCriterion("temp1 between", value1, value2, "temp1");
            return (Criteria) this;
        }

        public Criteria andTemp1NotBetween(String value1, String value2) {
            addCriterion("temp1 not between", value1, value2, "temp1");
            return (Criteria) this;
        }

        public Criteria andTemp2IsNull() {
            addCriterion("temp2 is null");
            return (Criteria) this;
        }

        public Criteria andTemp2IsNotNull() {
            addCriterion("temp2 is not null");
            return (Criteria) this;
        }

        public Criteria andTemp2EqualTo(String value) {
            addCriterion("temp2 =", value, "temp2");
            return (Criteria) this;
        }

        public Criteria andTemp2NotEqualTo(String value) {
            addCriterion("temp2 <>", value, "temp2");
            return (Criteria) this;
        }

        public Criteria andTemp2GreaterThan(String value) {
            addCriterion("temp2 >", value, "temp2");
            return (Criteria) this;
        }

        public Criteria andTemp2GreaterThanOrEqualTo(String value) {
            addCriterion("temp2 >=", value, "temp2");
            return (Criteria) this;
        }

        public Criteria andTemp2LessThan(String value) {
            addCriterion("temp2 <", value, "temp2");
            return (Criteria) this;
        }

        public Criteria andTemp2LessThanOrEqualTo(String value) {
            addCriterion("temp2 <=", value, "temp2");
            return (Criteria) this;
        }

        public Criteria andTemp2Like(String value) {
            addCriterion("temp2 like", value, "temp2");
            return (Criteria) this;
        }

        public Criteria andTemp2NotLike(String value) {
            addCriterion("temp2 not like", value, "temp2");
            return (Criteria) this;
        }

        public Criteria andTemp2In(List<String> values) {
            addCriterion("temp2 in", values, "temp2");
            return (Criteria) this;
        }

        public Criteria andTemp2NotIn(List<String> values) {
            addCriterion("temp2 not in", values, "temp2");
            return (Criteria) this;
        }

        public Criteria andTemp2Between(String value1, String value2) {
            addCriterion("temp2 between", value1, value2, "temp2");
            return (Criteria) this;
        }

        public Criteria andTemp2NotBetween(String value1, String value2) {
            addCriterion("temp2 not between", value1, value2, "temp2");
            return (Criteria) this;
        }

        public Criteria andTemp3IsNull() {
            addCriterion("temp3 is null");
            return (Criteria) this;
        }

        public Criteria andTemp3IsNotNull() {
            addCriterion("temp3 is not null");
            return (Criteria) this;
        }

        public Criteria andTemp3EqualTo(String value) {
            addCriterion("temp3 =", value, "temp3");
            return (Criteria) this;
        }

        public Criteria andTemp3NotEqualTo(String value) {
            addCriterion("temp3 <>", value, "temp3");
            return (Criteria) this;
        }

        public Criteria andTemp3GreaterThan(String value) {
            addCriterion("temp3 >", value, "temp3");
            return (Criteria) this;
        }

        public Criteria andTemp3GreaterThanOrEqualTo(String value) {
            addCriterion("temp3 >=", value, "temp3");
            return (Criteria) this;
        }

        public Criteria andTemp3LessThan(String value) {
            addCriterion("temp3 <", value, "temp3");
            return (Criteria) this;
        }

        public Criteria andTemp3LessThanOrEqualTo(String value) {
            addCriterion("temp3 <=", value, "temp3");
            return (Criteria) this;
        }

        public Criteria andTemp3Like(String value) {
            addCriterion("temp3 like", value, "temp3");
            return (Criteria) this;
        }

        public Criteria andTemp3NotLike(String value) {
            addCriterion("temp3 not like", value, "temp3");
            return (Criteria) this;
        }

        public Criteria andTemp3In(List<String> values) {
            addCriterion("temp3 in", values, "temp3");
            return (Criteria) this;
        }

        public Criteria andTemp3NotIn(List<String> values) {
            addCriterion("temp3 not in", values, "temp3");
            return (Criteria) this;
        }

        public Criteria andTemp3Between(String value1, String value2) {
            addCriterion("temp3 between", value1, value2, "temp3");
            return (Criteria) this;
        }

        public Criteria andTemp3NotBetween(String value1, String value2) {
            addCriterion("temp3 not between", value1, value2, "temp3");
            return (Criteria) this;
        }

        public Criteria andTemp4IsNull() {
            addCriterion("temp4 is null");
            return (Criteria) this;
        }

        public Criteria andTemp4IsNotNull() {
            addCriterion("temp4 is not null");
            return (Criteria) this;
        }

        public Criteria andTemp4EqualTo(String value) {
            addCriterion("temp4 =", value, "temp4");
            return (Criteria) this;
        }

        public Criteria andTemp4NotEqualTo(String value) {
            addCriterion("temp4 <>", value, "temp4");
            return (Criteria) this;
        }

        public Criteria andTemp4GreaterThan(String value) {
            addCriterion("temp4 >", value, "temp4");
            return (Criteria) this;
        }

        public Criteria andTemp4GreaterThanOrEqualTo(String value) {
            addCriterion("temp4 >=", value, "temp4");
            return (Criteria) this;
        }

        public Criteria andTemp4LessThan(String value) {
            addCriterion("temp4 <", value, "temp4");
            return (Criteria) this;
        }

        public Criteria andTemp4LessThanOrEqualTo(String value) {
            addCriterion("temp4 <=", value, "temp4");
            return (Criteria) this;
        }

        public Criteria andTemp4Like(String value) {
            addCriterion("temp4 like", value, "temp4");
            return (Criteria) this;
        }

        public Criteria andTemp4NotLike(String value) {
            addCriterion("temp4 not like", value, "temp4");
            return (Criteria) this;
        }

        public Criteria andTemp4In(List<String> values) {
            addCriterion("temp4 in", values, "temp4");
            return (Criteria) this;
        }

        public Criteria andTemp4NotIn(List<String> values) {
            addCriterion("temp4 not in", values, "temp4");
            return (Criteria) this;
        }

        public Criteria andTemp4Between(String value1, String value2) {
            addCriterion("temp4 between", value1, value2, "temp4");
            return (Criteria) this;
        }

        public Criteria andTemp4NotBetween(String value1, String value2) {
            addCriterion("temp4 not between", value1, value2, "temp4");
            return (Criteria) this;
        }

        public Criteria andTemp5IsNull() {
            addCriterion("temp5 is null");
            return (Criteria) this;
        }

        public Criteria andTemp5IsNotNull() {
            addCriterion("temp5 is not null");
            return (Criteria) this;
        }

        public Criteria andTemp5EqualTo(String value) {
            addCriterion("temp5 =", value, "temp5");
            return (Criteria) this;
        }

        public Criteria andTemp5NotEqualTo(String value) {
            addCriterion("temp5 <>", value, "temp5");
            return (Criteria) this;
        }

        public Criteria andTemp5GreaterThan(String value) {
            addCriterion("temp5 >", value, "temp5");
            return (Criteria) this;
        }

        public Criteria andTemp5GreaterThanOrEqualTo(String value) {
            addCriterion("temp5 >=", value, "temp5");
            return (Criteria) this;
        }

        public Criteria andTemp5LessThan(String value) {
            addCriterion("temp5 <", value, "temp5");
            return (Criteria) this;
        }

        public Criteria andTemp5LessThanOrEqualTo(String value) {
            addCriterion("temp5 <=", value, "temp5");
            return (Criteria) this;
        }

        public Criteria andTemp5Like(String value) {
            addCriterion("temp5 like", value, "temp5");
            return (Criteria) this;
        }

        public Criteria andTemp5NotLike(String value) {
            addCriterion("temp5 not like", value, "temp5");
            return (Criteria) this;
        }

        public Criteria andTemp5In(List<String> values) {
            addCriterion("temp5 in", values, "temp5");
            return (Criteria) this;
        }

        public Criteria andTemp5NotIn(List<String> values) {
            addCriterion("temp5 not in", values, "temp5");
            return (Criteria) this;
        }

        public Criteria andTemp5Between(String value1, String value2) {
            addCriterion("temp5 between", value1, value2, "temp5");
            return (Criteria) this;
        }

        public Criteria andTemp5NotBetween(String value1, String value2) {
            addCriterion("temp5 not between", value1, value2, "temp5");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sms_templates
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sms_templates
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}