package com.zjgt.p2p.report.model;

import java.util.Date;

public class Sms_templates {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_templates.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_templates.signboard
     *
     * @mbggenerated
     */
    private String signboard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_templates.ischeck
     *
     * @mbggenerated
     */
    private Integer ischeck;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_templates.checkname
     *
     * @mbggenerated
     */
    private String checkname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_templates.checktime
     *
     * @mbggenerated
     */
    private Date checktime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_templates.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_templates.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_templates.proposername
     *
     * @mbggenerated
     */
    private String proposername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_templates.proposertime
     *
     * @mbggenerated
     */
    private Date proposertime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_templates.proposerremark
     *
     * @mbggenerated
     */
    private String proposerremark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_templates.temp1
     *
     * @mbggenerated
     */
    private String temp1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_templates.temp2
     *
     * @mbggenerated
     */
    private String temp2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_templates.temp3
     *
     * @mbggenerated
     */
    private String temp3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_templates.temp4
     *
     * @mbggenerated
     */
    private String temp4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_templates.temp5
     *
     * @mbggenerated
     */
    private String temp5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_templates.template
     *
     * @mbggenerated
     */
    private String template;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_templates.id
     *
     * @return the value of sms_templates.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_templates.id
     *
     * @param id the value for sms_templates.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_templates.signboard
     *
     * @return the value of sms_templates.signboard
     *
     * @mbggenerated
     */
    public String getSignboard() {
        return signboard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_templates.signboard
     *
     * @param signboard the value for sms_templates.signboard
     *
     * @mbggenerated
     */
    public void setSignboard(String signboard) {
        this.signboard = signboard == null ? null : signboard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_templates.ischeck
     *
     * @return the value of sms_templates.ischeck
     *
     * @mbggenerated
     */
    public Integer getIscheck() {
        return ischeck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_templates.ischeck
     *
     * @param ischeck the value for sms_templates.ischeck
     *
     * @mbggenerated
     */
    public void setIscheck(Integer ischeck) {
        this.ischeck = ischeck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_templates.checkname
     *
     * @return the value of sms_templates.checkname
     *
     * @mbggenerated
     */
    public String getCheckname() {
        return checkname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_templates.checkname
     *
     * @param checkname the value for sms_templates.checkname
     *
     * @mbggenerated
     */
    public void setCheckname(String checkname) {
        this.checkname = checkname == null ? null : checkname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_templates.checktime
     *
     * @return the value of sms_templates.checktime
     *
     * @mbggenerated
     */
    public Date getChecktime() {
        return checktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_templates.checktime
     *
     * @param checktime the value for sms_templates.checktime
     *
     * @mbggenerated
     */
    public void setChecktime(Date checktime) {
        this.checktime = checktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_templates.createtime
     *
     * @return the value of sms_templates.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_templates.createtime
     *
     * @param createtime the value for sms_templates.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_templates.remark
     *
     * @return the value of sms_templates.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_templates.remark
     *
     * @param remark the value for sms_templates.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_templates.proposername
     *
     * @return the value of sms_templates.proposername
     *
     * @mbggenerated
     */
    public String getProposername() {
        return proposername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_templates.proposername
     *
     * @param proposername the value for sms_templates.proposername
     *
     * @mbggenerated
     */
    public void setProposername(String proposername) {
        this.proposername = proposername == null ? null : proposername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_templates.proposertime
     *
     * @return the value of sms_templates.proposertime
     *
     * @mbggenerated
     */
    public Date getProposertime() {
        return proposertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_templates.proposertime
     *
     * @param proposertime the value for sms_templates.proposertime
     *
     * @mbggenerated
     */
    public void setProposertime(Date proposertime) {
        this.proposertime = proposertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_templates.proposerremark
     *
     * @return the value of sms_templates.proposerremark
     *
     * @mbggenerated
     */
    public String getProposerremark() {
        return proposerremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_templates.proposerremark
     *
     * @param proposerremark the value for sms_templates.proposerremark
     *
     * @mbggenerated
     */
    public void setProposerremark(String proposerremark) {
        this.proposerremark = proposerremark == null ? null : proposerremark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_templates.temp1
     *
     * @return the value of sms_templates.temp1
     *
     * @mbggenerated
     */
    public String getTemp1() {
        return temp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_templates.temp1
     *
     * @param temp1 the value for sms_templates.temp1
     *
     * @mbggenerated
     */
    public void setTemp1(String temp1) {
        this.temp1 = temp1 == null ? null : temp1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_templates.temp2
     *
     * @return the value of sms_templates.temp2
     *
     * @mbggenerated
     */
    public String getTemp2() {
        return temp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_templates.temp2
     *
     * @param temp2 the value for sms_templates.temp2
     *
     * @mbggenerated
     */
    public void setTemp2(String temp2) {
        this.temp2 = temp2 == null ? null : temp2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_templates.temp3
     *
     * @return the value of sms_templates.temp3
     *
     * @mbggenerated
     */
    public String getTemp3() {
        return temp3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_templates.temp3
     *
     * @param temp3 the value for sms_templates.temp3
     *
     * @mbggenerated
     */
    public void setTemp3(String temp3) {
        this.temp3 = temp3 == null ? null : temp3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_templates.temp4
     *
     * @return the value of sms_templates.temp4
     *
     * @mbggenerated
     */
    public String getTemp4() {
        return temp4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_templates.temp4
     *
     * @param temp4 the value for sms_templates.temp4
     *
     * @mbggenerated
     */
    public void setTemp4(String temp4) {
        this.temp4 = temp4 == null ? null : temp4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_templates.temp5
     *
     * @return the value of sms_templates.temp5
     *
     * @mbggenerated
     */
    public String getTemp5() {
        return temp5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_templates.temp5
     *
     * @param temp5 the value for sms_templates.temp5
     *
     * @mbggenerated
     */
    public void setTemp5(String temp5) {
        this.temp5 = temp5 == null ? null : temp5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_templates.template
     *
     * @return the value of sms_templates.template
     *
     * @mbggenerated
     */
    public String getTemplate() {
        return template;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_templates.template
     *
     * @param template the value for sms_templates.template
     *
     * @mbggenerated
     */
    public void setTemplate(String template) {
        this.template = template == null ? null : template.trim();
    }
    
    
private String isCheck;
	
    public String getisCheck() {
  		return isCheck;
  	}

  	public void setisCheck(String isCheck) {
  		this.isCheck = isCheck;
  	}
  	
  	 private String isok;
 	
     public String getisok() {
   		return isok;
   	}

   	public void setisok(String isok) {
   		this.isok = isok;
   	}
  	
  	
    private String approve;
 	
    public String getapprove() {
  		return approve;
  	}

  	public void setapprove(String approve) {
  		this.approve = approve;
  	}
  	
  	private String checkStatus;
 	
    public String getcheckStatus() {
  		return checkStatus;
  	}

  	public void setcheckStatus(String checkStatus) {
  		this.checkStatus = checkStatus;
  	}
  	
  	private String search;
 	
    public String getsearch() {
  		return search;
  	}

  	public void setsearch(String search) {
  		this.search = search;
  	}
  	 private String isHave;

 	public String getIsHave() {
 		return isHave;
 	}

 	public void setIsHave(String isHave) {
 		this.isHave = isHave;
 	}

  	
 	private String projectType;
	
    public String getprojectType() {
  		return projectType;
  	}

  	public void setprojectType(String projectType) {
  		this.projectType = projectType;
  	}
}