package com.zjgt.p2p.report.model;

import java.util.Date;

public class smsMsgsource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_msgsource.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_msgsource.sourcecode
     *
     * @mbggenerated
     */
    private String sourcecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_msgsource.sourcename
     *
     * @mbggenerated
     */
    private String sourcename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_msgsource.createdate
     *
     * @mbggenerated
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_msgsource.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_msgsource.temp1
     *
     * @mbggenerated
     */
    private String temp1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_msgsource.temp2
     *
     * @mbggenerated
     */
    private String temp2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_msgsource.temp3
     *
     * @mbggenerated
     */
    private String temp3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_msgsource.temp4
     *
     * @mbggenerated
     */
    private String temp4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_msgsource.temp5
     *
     * @mbggenerated
     */
    private String temp5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_msgsource.id
     *
     * @return the value of sms_msgsource.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_msgsource.id
     *
     * @param id the value for sms_msgsource.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_msgsource.sourcecode
     *
     * @return the value of sms_msgsource.sourcecode
     *
     * @mbggenerated
     */
    public String getSourcecode() {
        return sourcecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_msgsource.sourcecode
     *
     * @param sourcecode the value for sms_msgsource.sourcecode
     *
     * @mbggenerated
     */
    public void setSourcecode(String sourcecode) {
        this.sourcecode = sourcecode == null ? null : sourcecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_msgsource.sourcename
     *
     * @return the value of sms_msgsource.sourcename
     *
     * @mbggenerated
     */
    public String getSourcename() {
        return sourcename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_msgsource.sourcename
     *
     * @param sourcename the value for sms_msgsource.sourcename
     *
     * @mbggenerated
     */
    public void setSourcename(String sourcename) {
        this.sourcename = sourcename == null ? null : sourcename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_msgsource.createdate
     *
     * @return the value of sms_msgsource.createdate
     *
     * @mbggenerated
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_msgsource.createdate
     *
     * @param createdate the value for sms_msgsource.createdate
     *
     * @mbggenerated
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_msgsource.remark
     *
     * @return the value of sms_msgsource.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_msgsource.remark
     *
     * @param remark the value for sms_msgsource.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_msgsource.temp1
     *
     * @return the value of sms_msgsource.temp1
     *
     * @mbggenerated
     */
    public String getTemp1() {
        return temp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_msgsource.temp1
     *
     * @param temp1 the value for sms_msgsource.temp1
     *
     * @mbggenerated
     */
    public void setTemp1(String temp1) {
        this.temp1 = temp1 == null ? null : temp1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_msgsource.temp2
     *
     * @return the value of sms_msgsource.temp2
     *
     * @mbggenerated
     */
    public String getTemp2() {
        return temp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_msgsource.temp2
     *
     * @param temp2 the value for sms_msgsource.temp2
     *
     * @mbggenerated
     */
    public void setTemp2(String temp2) {
        this.temp2 = temp2 == null ? null : temp2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_msgsource.temp3
     *
     * @return the value of sms_msgsource.temp3
     *
     * @mbggenerated
     */
    public String getTemp3() {
        return temp3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_msgsource.temp3
     *
     * @param temp3 the value for sms_msgsource.temp3
     *
     * @mbggenerated
     */
    public void setTemp3(String temp3) {
        this.temp3 = temp3 == null ? null : temp3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_msgsource.temp4
     *
     * @return the value of sms_msgsource.temp4
     *
     * @mbggenerated
     */
    public String getTemp4() {
        return temp4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_msgsource.temp4
     *
     * @param temp4 the value for sms_msgsource.temp4
     *
     * @mbggenerated
     */
    public void setTemp4(String temp4) {
        this.temp4 = temp4 == null ? null : temp4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_msgsource.temp5
     *
     * @return the value of sms_msgsource.temp5
     *
     * @mbggenerated
     */
    public String getTemp5() {
        return temp5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_msgsource.temp5
     *
     * @param temp5 the value for sms_msgsource.temp5
     *
     * @mbggenerated
     */
    public void setTemp5(String temp5) {
        this.temp5 = temp5 == null ? null : temp5.trim();
    }
    
    
    private String isCheck;

	public String getIsCheck() {
		return isCheck;
	}

	public void setIsCheck(String isCheck) {
		this.isCheck = isCheck;
	}
	
	 private String search;

	public String getSearch() {
		return search;
	}

	public void setSearch(String search) {
		this.search = search;
	}
	 
	 private String isHave;

	public String getIsHave() {
		return isHave;
	}

	public void setIsHave(String isHave) {
		this.isHave = isHave;
	}
	
	
	private String projectType;
	
    public String getprojectType() {
  		return projectType;
  	}

  	public void setprojectType(String projectType) {
  		this.projectType = projectType;
  	}
}